//CAREGA A BIBLIOTECA PARA O MICROCONTROLADOR PIC16F628A
#INCLUDE <16F628A.h>
//CONFIGURACAO DOS FUSES
#FUSES NOWDT
#FUSES NOPUT
#FUSES NOBROWNOUT
#FUSES NOMCLR
#FUSES NOLVP
#FUSES NOCPD
//DEFINE A UTILIZACAO DO CLOCK INTERNO 
#use delay(clock=4000000)
//PINO AO QUAL O TRANSISTOR ESTA LIGADO
#DEFINE PINOTRANSISTOR PIN_B0
void main(){
  
    while(true){
      OUTPUT_BIT(PINOTRANSISTOR, true); //LIGA O TRANSISTOR
      DELAY_MS(1000); //AGUARDA 1 SEGUNDO
      OUTPUT_BIT(PINOTRANSISTOR,false); //DESLIGA O TRANSISTOR
      DELAY_MS(1000); //AGUARDA 2 SEGUNDO
    }
}

